#!/bin/sh
# 
# jeee commander
#

# loads functions
. ./jeee.func

OPTS=`getopt -o hiuqrw: --long help,install,uninstall,quit,remove,add-workspace: -n 'parse-options' -- "$@"`

if [ $? != 0 ] ; then echo "Failed parsing options." >&2 ; exit 1 ; fi

echo "$OPTS"
eval set -- "$OPTS"

HELP=false
INSTALL=false
QUIT=false
REMOVE=false



while true; do
  case "$1" in
    -h | --help ) HELP=true; shift ; break ;;
    -i | --install ) INSTALL=true; shift ;;
    -q | --quit ) QUIT=true; shift ;;
    -r | --remove ) REMOVE=true; shift ;;
    -- ) shift ;;
    * ) if [ -z "$1" ]; then run; fi; break ;;
  esac
done


echo HELP=$HELP
echo INSTALL=$INSTALL
echo QUIT=$QUIT
echo REMOVE=$REMOVE